// ─────────────────────────────────────────────────────────────────────────────
// Social Feed Generation Engine — Domain Types, Interfaces & Stubs
//
// This file defines the complete public contract (interfaces) and the stub
// implementations (classes with unimplemented methods) for the TDD capstone.
//
// Architecture overview:
//   FanOutWorker  — Consumes "post.created" broker events and decides whether
//                   to push posts to follower caches (normal user) or skip
//                   fan-out entirely (celebrity / influencer).
//
//   FeedService   — Assembles the home timeline for a requesting user via a
//                   hybrid strategy: reads the pre-computed Redis cache (push
//                   path) and merges celebrity posts queried on-the-fly (pull
//                   path). Handles cache-miss hydration for inactive users.
//
//   APIGateway    — Validates JWT Authorization headers, resolves the target
//                   microservice from the URL path, and injects X-User-Id into
//                   downstream request headers.
//
// TDD guidance:
//   All class methods deliberately throw "not implemented" errors. Your task is
//   to replace each throw with a correct implementation that makes the Vitest
//   test suite go from Red → Green. Follow the pseudocode in each method's
//   JSDoc comment block as your implementation guide.
// ─────────────────────────────────────────────────────────────────────────────

// ─── Domain Types ─────────────────────────────────────────────────────────────

/**
 * Represents a single piece of user-generated content persisted in PostgreSQL.
 *
 * Maps directly to the `posts` table row. The `id` field is a UUID generated
 * by the database (`gen_random_uuid()`). The `createdAt` timestamp is used as
 * the Redis Sorted Set score (converted to Unix epoch milliseconds) to ensure
 * chronological ordering in the timeline cache.
 *
 * @example
 * const post: Post = {
 *   id: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
 *   authorId: "user-alice",
 *   content: "Hello, world!",
 *   createdAt: new Date("2024-01-15T10:00:00Z"),
 * };
 */
export interface Post {
  /** UUID primary key — generated by PostgreSQL gen_random_uuid() */
  id: string;
  /** Foreign key → users.id (the author of the post) */
  authorId: string;
  /** The textual content of the post (1–280 characters) */
  content: string;
  /**
   * ISO 8601 timestamp of creation.
   * Used as the Sorted Set score: `createdAt.getTime()` → epoch milliseconds.
   * Higher score = more recent = appears earlier in the timeline.
   */
  createdAt: Date;
}

/**
 * Represents a registered user account fetched from PostgreSQL.
 *
 * The `followerCount` field is the key discriminator between normal users and
 * celebrities. It is denormalized (maintained by a database trigger — see the
 * schema section in README) to avoid an expensive `COUNT(*)` query on the
 * `follows` table during every fan-out decision.
 *
 * Celebrity threshold: `followerCount > CELEBRITY_FOLLOWER_THRESHOLD (10,000)`
 *
 * @example
 * // Normal user — fan-out on WRITE (push path)
 * const alice: User = { id: "u1", username: "alice", followerCount: 342 };
 *
 * // Celebrity — fan-out on READ (pull path; no cache push)
 * const popStar: User = { id: "u2", username: "mega_star", followerCount: 5_200_000 };
 */
export interface User {
  /** UUID primary key */
  id: string;
  /** Unique handle — used for display and URL routing */
  username: string;
  /**
   * Cached follower count. Updated transactionally when follows are
   * inserted or deleted (database trigger). This is the single field
   * that controls whether a user is treated as a celebrity (pull path)
   * or a normal user (push path).
   *
   * Accounts with > 10,000 followers are treated as celebrities (pull path).
   */
  followerCount: number;
}

/**
 * A single entry in a user's home timeline as returned by the Feed Service.
 *
 * FeedEntry is the read model — it flattens the post data so the client does
 * not need to make a second request to resolve post content. The `source`
 * field tracks how this entry arrived in the timeline for observability and
 * A/B testing:
 *   - "push" → entry was pre-computed by the fan-out worker into Redis.
 *   - "pull" → entry was fetched from PostgreSQL at read time (celebrity path).
 *
 * @example
 * const entry: FeedEntry = {
 *   postId:    "post-abc",
 *   authorId:  "user-celeb",
 *   content:   "Big announcement!",
 *   createdAt: new Date("2024-01-15T12:00:00Z"),
 *   source:    "pull",   // fetched from DB at feed-read time
 * };
 */
export interface FeedEntry {
  /** UUID of the backing post in PostgreSQL */
  postId: string;
  /** UUID of the user who authored the post */
  authorId: string;
  /** Denormalized post content — avoids a second DB round-trip on read */
  content: string;
  /**
   * Timestamp used for chronological sorting.
   * When merging push + pull entries, sort descending by this field.
   */
  createdAt: Date;
  /**
   * Tracks the delivery mechanism for analytics and debugging.
   * - "push": arrived via fan-out worker → already in Redis before read.
   * - "pull": fetched from PostgreSQL at read time (celebrity, or cache-miss).
   */
  source: "push" | "pull";
}

// ─── Database Adapter (PostgreSQL mock contract) ────────────────────────────

/**
 * IDatabase — Abstraction over the PostgreSQL persistence layer.
 *
 * In production this is implemented by a `pg.Pool`-backed class that issues
 * parameterized SQL queries. In tests it is replaced with an in-memory mock
 * (`mockDb`) so the test suite does not require a live PostgreSQL instance.
 *
 * WHY AN INTERFACE?
 *   Separating the contract (IDatabase) from the implementation (PostgresDatabase)
 *   allows the FanOutWorker and FeedService to be tested in complete isolation
 *   from the database. This is the Dependency Inversion Principle in action.
 *
 * REDIS/SQL MAPPING:
 *   savePost               → INSERT INTO posts (...) RETURNING *
 *   getFollowers           → SELECT follower_id FROM follows WHERE followee_id = $1
 *   getRecentPostsByAuthors → SELECT * FROM posts WHERE author_id = ANY($1)
 *                             ORDER BY created_at DESC LIMIT $2
 *   getUser                → SELECT * FROM users WHERE id = $1
 */
export interface IDatabase {
  /**
   * Persists a new post to the `posts` table and returns the full row with
   * the database-assigned `id`.
   *
   * SQL equivalent:
   * ```sql
   * INSERT INTO posts (author_id, content, created_at)
   * VALUES ($1, $2, $3)
   * RETURNING *;
   * ```
   *
   * @param post - All post fields except `id` (generated by the database).
   * @returns The saved post including its newly assigned UUID.
   *
   * @example
   * const saved = await db.savePost({ authorId: "u1", content: "Hi!", createdAt: new Date() });
   * console.log(saved.id); // "f47ac10b-..."
   */
  savePost(post: Omit<Post, "id">): Promise<Post>;

  /**
   * Retrieves the list of user IDs who follow the given user.
   *
   * Used by FanOutWorker to determine which users' Redis timelines should
   * receive a push notification for a new post.
   *
   * SQL equivalent:
   * ```sql
   * SELECT follower_id FROM follows WHERE followee_id = $1;
   * ```
   *
   * Performance note: This query uses the `idx_follows_followee` index.
   * For celebrities (millions of followers) this can return a very large
   * result set — which is why celebrities are exempted from push fan-out.
   *
   * @param userId - The author's user ID (the "followee" in the social graph).
   * @returns An array of follower user IDs. May be empty for users with no followers.
   *
   * @example
   * const followers = await db.getFollowers("user-alice");
   * // ["user-bob", "user-carol", "user-dave"]
   */
  getFollowers(userId: string): Promise<string[]>;

  /**
   * Returns the N most recent posts authored by any of the given user IDs,
   * sorted newest-first.
   *
   * Used in two contexts:
   *   1. Celebrity pull-path: fetch recent posts from celebrities the reader follows.
   *   2. Cache-miss hydration: fetch all recent posts from everyone the reader follows.
   *
   * SQL equivalent:
   * ```sql
   * SELECT * FROM posts
   * WHERE author_id = ANY($1)
   *   AND deleted_at IS NULL
   * ORDER BY created_at DESC
   * LIMIT $2;
   * ```
   *
   * Performance note: Uses `idx_posts_author_created` index.
   * Never call this in a loop (N+1 anti-pattern). Always batch all authorIds.
   *
   * @param userIds - Array of author IDs. Pass all celebrity IDs at once.
   * @param limit   - Maximum number of posts to return (e.g., 20 or 100).
   * @returns Posts sorted by `createdAt` descending.
   *
   * @example
   * const posts = await db.getRecentPostsByAuthors(["celeb-1", "celeb-2"], 20);
   */
  getRecentPostsByAuthors(userIds: string[], limit: number): Promise<Post[]>;

  /**
   * Fetches a single user record including their cached follower count.
   *
   * Used by FanOutWorker before deciding the fan-out strategy:
   *   - If `user.followerCount > CELEBRITY_FOLLOWER_THRESHOLD` → skip push fan-out.
   *   - Otherwise → proceed with push fan-out to active followers.
   *
   * SQL equivalent:
   * ```sql
   * SELECT * FROM users WHERE id = $1;
   * ```
   *
   * @param userId - UUID of the user to fetch.
   * @returns The User record, or `null` if no user with that ID exists.
   *
   * @example
   * const author = await db.getUser("author-1");
   * if (!author) throw new Error("Author not found");
   * if (author.followerCount > CELEBRITY_FOLLOWER_THRESHOLD) {
   *   // Celebrity — skip push fan-out
   * }
   */
  getUser(userId: string): Promise<User | null>;
}

// ─── Cache Adapter (Redis mock contract) ────────────────────────────────────

/**
 * ICache — Abstraction over the Redis Sorted-Set based timeline cache.
 *
 * Key convention: `feed:<userId>`
 *   Score = `post.createdAt.getTime()` (Unix milliseconds)
 *   Member = post ID string (e.g., "post-abc123")
 *
 * WHY SORTED SETS?
 *   Redis Sorted Sets (ZSET) store members with a floating-point score.
 *   Using the creation timestamp as the score gives us:
 *     - O(log N) insertion  → ZADD
 *     - O(log N + M) range read newest-first  → ZREVRANGE / ZREVRANGEBYSCORE
 *     - Automatic deduplication: adding the same postId twice with different
 *       scores just updates the score — no double entries.
 *
 * PRODUCTION NOTE:
 *   In a real implementation, also call `ZREMRANGEBYRANK feed:userId 0 -1001`
 *   after every ZADD to cap the feed at 1000 entries and prevent unbounded growth.
 */
export interface ICache {
  /**
   * Pushes a single FeedEntry into a user's cached timeline sorted set.
   *
   * Redis operation:
   * ```
   * ZADD feed:<userId> <entry.createdAt.getTime()> <entry.postId>
   * ```
   *
   * Called by FanOutWorker for each active follower of a normal (non-celebrity) author.
   * The caller MUST first check `hasFeed(userId)` to avoid creating Redis keys for
   * inactive users (see Pitfall 1 in README).
   *
   * @param userId - The follower's user ID (receives the new post in their timeline).
   * @param entry  - The FeedEntry to add (source should be "push" for fan-out).
   *
   * @example
   * await cache.pushToFeed("user-B", {
   *   postId:    "post-abc",
   *   authorId:  "author-1",
   *   content:   "Hello!",
   *   createdAt: new Date(),
   *   source:    "push",
   * });
   */
  pushToFeed(userId: string, entry: FeedEntry): Promise<void>;

  /**
   * Retrieves the most recent `limit` entries from a user's cached timeline.
   *
   * Redis operation:
   * ```
   * ZREVRANGE feed:<userId> 0 <limit-1> WITHSCORES
   * ```
   * Returns entries in descending score order (newest first).
   *
   * After calling `getFeed`, always refresh the TTL (call `hydrateFeed` or
   * issue `EXPIRE`) to implement the sliding 72-hour window.
   *
   * @param userId - The requesting user's ID.
   * @param limit  - Maximum number of entries to return (e.g., 20).
   * @returns An ordered array of FeedEntry objects, newest first.
   *          Returns an empty array if no cache exists for the user.
   *
   * @example
   * const entries = await cache.getFeed("user-B", 20);
   * // [{ postId: "latest-post", source: "push", ... }, ...]
   */
  getFeed(userId: string, limit: number): Promise<FeedEntry[]>;

  /**
   * Returns true if the user has an active, non-empty cached feed in Redis.
   *
   * Redis operation:
   * ```
   * EXISTS feed:<userId>   → 1 if key exists, 0 if not
   * ZCARD  feed:<userId>   → count of members (>0 means active)
   * ```
   *
   * Used by FanOutWorker to determine whether a follower's cache should
   * receive a push. Inactive users (no cache) are skipped to avoid wasting
   * Redis memory on users who may never return.
   *
   * @param userId - The user ID to check.
   * @returns `true` if the user has an active cached timeline; `false` otherwise.
   *
   * @example
   * const isActive = await cache.hasFeed("user-C");
   * if (isActive) {
   *   await cache.pushToFeed("user-C", newEntry);
   * }
   */
  hasFeed(userId: string): Promise<boolean>;

  /**
   * Seeds (or re-seeds) a user's timeline cache with a batch of FeedEntries
   * and sets a TTL on the key.
   *
   * Redis operations:
   * ```
   * DEL feed:<userId>                          // Clear any stale data
   * ZADD feed:<userId> <score> <member> ...    // Add all entries at once
   * EXPIRE feed:<userId> <ttlSeconds>          // Set expiry
   * ```
   *
   * Called in two scenarios:
   *   1. **Cache-miss hydration**: When an inactive or new user requests their
   *      feed and there is no existing Redis key. The FeedService queries
   *      PostgreSQL, then calls hydrateFeed to populate Redis.
   *   2. **TTL refresh**: After serving a cached feed, call hydrateFeed with
   *      the same entries and `ttlSeconds = 72 * 3600` to extend the sliding
   *      expiry window (see Pitfall 2 in README).
   *
   * @param userId     - The user whose feed is being hydrated.
   * @param entries    - The complete set of FeedEntry objects to write to Redis.
   * @param ttlSeconds - Expiry in seconds. Standard value: `72 * 3600 = 259200`.
   *
   * @example
   * // Cache-miss: hydrate from DB with 72-hour TTL
   * await cache.hydrateFeed("inactive-user", dbPosts, 72 * 3600);
   */
  hydrateFeed(userId: string, entries: FeedEntry[], ttlSeconds: number): Promise<void>;
}

// ─── Message Broker Adapter (RabbitMQ/Kafka mock contract) ──────────────────

/**
 * IMessageBroker — Abstraction over the async event bus (RabbitMQ or Kafka).
 *
 * Publishing a "post.created" event decouples the HTTP write path from the
 * fan-out computation. The Post Service returns HTTP 201 to the author
 * immediately after publishing the event — fans receive the post asynchronously
 * via the fan-out worker processing the queue.
 *
 * WHY AN INTERFACE?
 *   In tests, IMessageBroker is replaced with a vi.fn() mock so we can assert
 *   that events are published without actually connecting to RabbitMQ.
 *
 * RabbitMQ mapping:
 *   publishPostCreated → channel.publish("post.events", "post.created", Buffer.from(JSON.stringify(post)))
 *
 * Kafka mapping:
 *   publishPostCreated → producer.send({ topic: "post.created", messages: [{ key: post.authorId, value: JSON.stringify(post) }] })
 */
export interface IMessageBroker {
  /**
   * Publishes a "post.created" event to the message broker so that
   * fan-out workers can consume it asynchronously.
   *
   * This method should be fire-and-forget from the HTTP handler's perspective:
   * await it for guaranteed delivery, then return HTTP 201 without waiting
   * for fan-out to complete.
   *
   * @param post - The full Post object that was just persisted to the database.
   *               Fan-out workers will use post.authorId to look up the author
   *               and determine the fan-out strategy.
   *
   * @example
   * const saved = await db.savePost(newPostData);
   * await broker.publishPostCreated(saved); // Non-blocking from user's perspective
   * return { status: 201, postId: saved.id };
   */
  publishPostCreated(post: Post): Promise<void>;
}

// ─── Follow Service Interface ────────────────────────────────────────────────

/**
 * IFollowService — Abstraction for checking the celebrity status of a user
 * and retrieving targeted follow-relationship queries used during feed assembly.
 *
 * WHY A SEPARATE INTERFACE FROM IDatabase?
 *   In the microservices topology, the Follow Service is a separate process
 *   (Node.js microservice). The FeedService and FanOutWorker communicate with
 *   it via HTTP or gRPC — NOT via direct DB queries. This interface models
 *   that network call boundary.
 *
 *   The IDatabase.getFollowers method is used internally (within the same
 *   service boundary). IFollowService models the cross-service call that
 *   could be implemented as an HTTP client in production.
 *
 * CONTRACT:
 *   - isCelebrity(userId) → true if followerCount > CELEBRITY_FOLLOWER_THRESHOLD
 *   - getCelebFollowees(userId) → IDs of users that `userId` follows AND who
 *     are celebrities (used to select the pull-path authors during feed read).
 */
export interface IFollowService {
  /**
   * Returns true if the given user qualifies as a "celebrity" — meaning their
   * follower count exceeds CELEBRITY_FOLLOWER_THRESHOLD (10,000).
   *
   * Used by FanOutWorker before deciding the fan-out strategy for a new post.
   * Using this interface method instead of directly calling IDatabase.getUser
   * keeps the worker decoupled from the persistence layer.
   *
   * Implementation note:
   *   Internally, this maps to: db.getUser(userId).then(u => u.followerCount > CELEBRITY_FOLLOWER_THRESHOLD)
   *
   * @param userId - The user ID to check celebrity status for.
   * @returns Promise<boolean> — true if celebrity, false if normal user.
   *
   * @example
   * if (await followService.isCelebrity(post.authorId)) {
   *   return { pushedTo: 0 }; // Skip push fan-out
   * }
   */
  isCelebrity(userId: string): Promise<boolean>;

  /**
   * Returns the IDs of all accounts that `userId` follows AND who are
   * celebrities (followerCount > CELEBRITY_FOLLOWER_THRESHOLD).
   *
   * Used by FeedService during the hybrid timeline assembly to identify
   * which followed accounts need a pull-path query (instead of relying
   * on the pre-computed Redis cache).
   *
   * Implementation note:
   *   This could be a single SQL query:
   *   ```sql
   *   SELECT f.followee_id
   *   FROM follows f
   *   JOIN users u ON u.id = f.followee_id
   *   WHERE f.follower_id = $1
   *     AND u.follower_count > $2;
   *   ```
   *
   * @param userId    - The timeline reader's user ID.
   * @param threshold - The follower count above which an account is a celebrity.
   *                    Defaults to CELEBRITY_FOLLOWER_THRESHOLD.
   * @returns An array of user IDs (celebrity followees of `userId`).
   *
   * @example
   * const celebIds = await followService.getCelebFollowees("reader-1", 10000);
   * const celebPosts = await db.getRecentPostsByAuthors(celebIds, 20);
   */
  getCelebFollowees(userId: string, threshold?: number): Promise<string[]>;
}

// ─── Fan-Out Worker ──────────────────────────────────────────────────────────

/**
 * Celebrity threshold — the follower count above which a user is classified as
 * an "influencer" and their posts are excluded from the write-path fan-out.
 *
 * This constant is exported so tests can reference it symbolically (avoid
 * magic numbers). In production, load this from an environment variable:
 *   `Number(process.env.CELEBRITY_THRESHOLD ?? 10_000)`
 */
export const CELEBRITY_FOLLOWER_THRESHOLD = 10_000;

/**
 * FanOutWorker — Consumes "post.created" broker events and routes them through
 * the hybrid fan-out decision tree.
 *
 * RESPONSIBILITY:
 *   For every post event consumed from the message broker, the worker:
 *   1. Looks up the author's follower count from the database.
 *   2. If the author is a celebrity (count > 10,000): returns immediately with
 *      pushedTo = 0 (followers will pull on read via the DB query path).
 *   3. If the author is a normal user: queries all follower IDs, then for each
 *      active follower (one with an existing Redis cache), calls pushToFeed.
 *
 * DESIGN NOTES:
 *   - The worker intentionally does NOT create new cache keys for inactive
 *     followers. Inactive users' feeds are reconstructed on-demand when they
 *     next request their timeline (hydration path in FeedService).
 *   - Fan-out is O(F) where F = number of active followers. For users with
 *     thousands of active followers, this runs as a batch loop. In production,
 *     this loop is parallelized with Promise.allSettled and bounded concurrency.
 */
export class FanOutWorker {
  constructor(
    private db: IDatabase,
    private cache: ICache,
  ) {}

  /**
   * Process a single "post.created" event from the message broker.
   *
   * FULL ALGORITHM (implement this step-by-step):
   *
   * ```
   * Step 1 — Fetch author metadata:
   *   const author = await this.db.getUser(post.authorId)
   *   if (author === null) → throw Error or return { pushedTo: 0 }
   *
   * Step 2 — Celebrity check:
   *   if (author.followerCount > CELEBRITY_FOLLOWER_THRESHOLD):
   *     → return { pushedTo: 0 }  // Do NOT push to any follower cache
   *     // Followers will pull celebrity posts at read time via the DB
   *
   * Step 3 — Fetch all follower IDs:
   *   const followerIds = await this.db.getFollowers(post.authorId)
   *
   * Step 4 — Filter to active followers only:
   *   let pushedTo = 0
   *   for each followerId in followerIds:
   *     const isActive = await this.cache.hasFeed(followerId)
   *     if (isActive):
   *       Step 5 — Build the FeedEntry:
   *         const entry: FeedEntry = {
   *           postId:    post.id,
   *           authorId:  post.authorId,
   *           content:   post.content,
   *           createdAt: post.createdAt,
   *           source:    "push",
   *         }
   *       Step 6 — Push to the active follower's Redis sorted set:
   *         await this.cache.pushToFeed(followerId, entry)
   *         pushedTo++
   *     else:
   *       // Skip inactive follower — they'll pull on next login
   *
   * Step 7 — Return the count of caches updated:
   *   return { pushedTo }
   * ```
   *
   * EDGE CASES TO HANDLE:
   *   - `author === null`: The user may have been deleted between posting and
   *     fan-out. Treat as "0 followers notified" and return { pushedTo: 0 }.
   *   - `followerIds === []`: No followers yet (new user). Return { pushedTo: 0 }.
   *   - All followers inactive: Valid scenario. Return { pushedTo: 0 }.
   *
   * PERFORMANCE HINT:
   *   In production, replace the sequential for-loop with a parallelized batch:
   *   ```typescript
   *   const results = await Promise.allSettled(
   *     followerIds.map(async (id) => {
   *       if (await this.cache.hasFeed(id)) {
   *         await this.cache.pushToFeed(id, entry);
   *         return 1;
   *       }
   *       return 0;
   *     })
   *   );
   *   const pushedTo = results.filter(r => r.status === "fulfilled" && r.value === 1).length;
   *   ```
   *
   * @param post - The full Post object consumed from the "post.created" event.
   * @returns `{ pushedTo: number }` — the count of active follower caches updated.
   *          For celebrity authors, this is always 0.
   *
   * TDD Starter: method is intentionally not implemented — tests will fail (Red state).
   */
  async processPostCreated(post: Post): Promise<{ pushedTo: number }> {
    const author = await this.db.getUser(post.authorId);
    if (author === null) {
      return { pushedTo: 0 };
    }

    if (author.followerCount > CELEBRITY_FOLLOWER_THRESHOLD) {
      return { pushedTo: 0 };
    }

    const followerIds = await this.db.getFollowers(post.authorId);
    let pushedTo = 0;

    for (const followerId of followerIds) {
      const isActive = await this.cache.hasFeed(followerId);
      if (isActive) {
        const entry: FeedEntry = {
          postId: post.id,
          authorId: post.authorId,
          content: post.content,
          createdAt: post.createdAt,
          source: "push",
        };
        await this.cache.pushToFeed(followerId, entry);
        pushedTo++;
      }
    }

    return { pushedTo };
  }
}

// ─── Feed Service ─────────────────────────────────────────────────────────────

/**
 * FeedService — Assembles the home timeline for a requesting user via the
 * hybrid push + pull strategy.
 *
 * RESPONSIBILITY:
 *   For every timeline request:
 *   1. Check if the user has an active feed in Redis (hasFeed).
 *   2. Cache HIT (active user):
 *      a. Fetch the pre-computed push entries from Redis.
 *      b. Identify which of the user's followees are celebrities.
 *      c. Query PostgreSQL for recent celebrity posts.
 *      d. Merge both arrays chronologically and return the top `limit` entries.
 *      e. Refresh the Redis TTL (sliding 72-hour window).
 *   3. Cache MISS (inactive/new user):
 *      a. Query PostgreSQL for all recent posts from everyone the user follows.
 *      b. Hydrate the Redis cache with the results (72-hour TTL).
 *      c. Return the results.
 *
 * DESIGN NOTES:
 *   - The FeedService NEVER calls pushToFeed — that is the FanOutWorker's job.
 *   - Celebrity detection in the cache-hit path requires a DB/follow-service
 *     call to identify which followees are celebrities (followerCount > threshold).
 *   - The merge step must sort descending by `createdAt` and must not exceed
 *     `limit` entries in the final result.
 */
export class FeedService {
  constructor(
    private db: IDatabase,
    private cache: ICache,
  ) {}

  /**
   * Build the home timeline for `userId`.
   *
   * FULL ALGORITHM (implement both paths):
   *
   * === PATH A: Cache HIT (active user) ===
   * ```
   * Step 1 — Check cache:
   *   const hasCachedFeed = await this.cache.hasFeed(userId)
   *   → if false, go to PATH B
   *
   * Step 2 — Fetch pre-computed push entries:
   *   const pushEntries = await this.cache.getFeed(userId, limit)
   *   // These are posts from non-celebrity accounts, already sorted newest-first
   *
   * Step 3 — Find celebrity followees:
   *   const followedIds = await this.db.getFollowers(userId)
   *   // NOTE: getFollowers returns who the user follows (the IDatabase contract)
   *   // Clarification: in tests, db.getFollowers(userId) returns the list of
   *   // authors the requesting user follows (their "following" list).
   *   const celebrityIds: string[] = []
   *   for each followedId in followedIds:
   *     const user = await this.db.getUser(followedId)
   *     if (user && user.followerCount > CELEBRITY_FOLLOWER_THRESHOLD):
   *       celebrityIds.push(followedId)
   *
   * Step 4 — Pull celebrity posts from DB:
   *   const celebPosts = await this.db.getRecentPostsByAuthors(celebrityIds, limit)
   *   const pullEntries: FeedEntry[] = celebPosts.map(p => ({
   *     postId:    p.id,
   *     authorId:  p.authorId,
   *     content:   p.content,
   *     createdAt: p.createdAt,
   *     source:    "pull",
   *   }))
   *
   * Step 5 — Merge & sort:
   *   const merged = [...pushEntries, ...pullEntries]
   *     .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
   *     .slice(0, limit)
   *
   * Step 6 — Refresh TTL (sliding window):
   *   await this.cache.hydrateFeed(userId, merged, 72 * 3600)
   *
   * Step 7 — Return merged timeline:
   *   return merged
   * ```
   *
   * === PATH B: Cache MISS (inactive/new user) ===
   * ```
   * Step 1 — Fetch all followed author IDs:
   *   const followedIds = await this.db.getFollowers(userId)
   *
   * Step 2 — Query all recent posts from followed accounts:
   *   const allPosts = await this.db.getRecentPostsByAuthors(followedIds, limit * 5)
   *   // Fetch 5x limit to give the cache enough data for future reads
   *
   * Step 3 — Convert to FeedEntries:
   *   const entries: FeedEntry[] = allPosts.map(p => ({
   *     postId:    p.id,
   *     authorId:  p.authorId,
   *     content:   p.content,
   *     createdAt: p.createdAt,
   *     source:    "pull",
   *   }))
   *
   * Step 4 — Hydrate Redis cache with 72-hour TTL:
   *   await this.cache.hydrateFeed(userId, entries, 72 * 3600)
   *   // Future requests from this user will hit PATH A (cache-hit)
   *
   * Step 5 — Return the page of results:
   *   return entries.slice(0, limit)
   * ```
   *
   * EDGE CASES TO HANDLE:
   *   - User follows nobody: return [] (no posts to show).
   *   - All followees are celebrities + cache hit: pushEntries is empty, only pull entries returned.
   *   - Celebrity IDs list is empty: skip getRecentPostsByAuthors call (avoid empty IN() query).
   *   - `limit` < 1: treat as 1 (defensive guard).
   *
   * @param userId - The requesting user's ID.
   * @param limit  - Maximum number of FeedEntry objects to return (e.g., 20).
   * @returns Chronologically sorted FeedEntry array (newest first), at most `limit` items.
   *
   * TDD Starter: method is intentionally not implemented — tests will fail (Red state).
   */
  async getTimeline(userId: string, limit: number): Promise<FeedEntry[]> {
    const finalLimit = limit < 1 ? 1 : limit;
    const hasCachedFeed = await this.cache.hasFeed(userId);

    if (hasCachedFeed) {
      const pushEntries = await this.cache.getFeed(userId, finalLimit);
      const followedIds = await this.db.getFollowers(userId);
      if (followedIds.length === 0) {
        return pushEntries.slice(0, finalLimit);
      }

      const celebrityIds: string[] = [];
      for (const followedId of followedIds) {
        const user = await this.db.getUser(followedId);
        if (user && user.followerCount > CELEBRITY_FOLLOWER_THRESHOLD) {
          celebrityIds.push(followedId);
        }
      }

      let pullEntries: FeedEntry[] = [];
      if (celebrityIds.length > 0) {
        const celebPosts = await this.db.getRecentPostsByAuthors(celebrityIds, finalLimit);
        pullEntries = celebPosts.map(p => ({
          postId: p.id,
          authorId: p.authorId,
          content: p.content,
          createdAt: p.createdAt,
          source: "pull",
        }));
      }

      const merged = [...pushEntries, ...pullEntries]
        .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
        .slice(0, finalLimit);

      await this.cache.hydrateFeed(userId, merged, 72 * 3600);
      return merged;
    } else {
      const followedIds = await this.db.getFollowers(userId);
      if (followedIds.length === 0) {
        await this.cache.hydrateFeed(userId, [], 72 * 3600);
        return [];
      }

      const allPosts = await this.db.getRecentPostsByAuthors(followedIds, finalLimit * 5);
      const entries: FeedEntry[] = allPosts.map(p => ({
        postId: p.id,
        authorId: p.authorId,
        content: p.content,
        createdAt: p.createdAt,
        source: "pull",
      }));

      await this.cache.hydrateFeed(userId, entries, 72 * 3600);
      return entries.slice(0, finalLimit);
    }
  }
}

// ─── API Gateway Simulation ───────────────────────────────────────────────────

/**
 * Represents an inbound HTTP-like request arriving at the API Gateway.
 *
 * In production this maps to an Express/Fastify `Request` object. In this
 * simulation it is a plain data bag passed to `APIGateway.handleRequest`.
 *
 * The `authorization` header must be present and follow the format:
 *   `Authorization: Bearer <token>`
 * The token format for stubs: `<base64payload>.<signature>`
 * where the base64 payload decodes to JSON: `{ "sub": "<userId>", "role": "user" }`
 */
export interface GatewayRequest {
  /** URL path of the request, e.g. "/api/v1/posts/create" */
  path: string;
  /**
   * HTTP headers as a flat string map. The gateway inspects:
   *   - `authorization`: Required for JWT validation. Must start with "Bearer ".
   * After validation, the gateway INJECTS:
   *   - `x-user-id`: Extracted userId from the JWT, forwarded to downstream services.
   */
  headers: Record<string, string>;
  /** Optional request body (for POST/PUT requests). Passed through to the service. */
  body?: unknown;
}

/**
 * Represents the API Gateway's response to the client after routing.
 *
 * The gateway does NOT relay the downstream service's raw response body in this
 * simulation. Instead it returns a structured object indicating the HTTP status,
 * the service name the request was routed to, and any routing-layer errors.
 */
export interface GatewayResponse {
  /**
   * HTTP status code:
   *   200 — Successfully routed to a downstream service.
   *   401 — Authorization header missing or JWT invalid.
   *   404 — No service registered for this path.
   */
  status: number;
  /**
   * The name of the downstream service the request was routed to.
   * Examples: "PostService", "FeedService", "FollowService".
   * Empty string if routing failed (status 401 or 404).
   */
  service: string;
  /**
   * Arbitrary response data from the downstream service (opaque payload in
   * this simulation). May include the forwarded userId for test assertions.
   */
  data?: unknown;
  /**
   * Human-readable error message for failed requests (status 401 or 404).
   * Should match: /unauthorized/i for 401, /not found/i for 404.
   */
  error?: string;
}

/**
 * IServiceRegistry — Maps URL path prefixes to named downstream services.
 *
 * WHY AN INTERFACE?
 *   Separating the routing table from the Gateway implementation allows the
 *   registry to be mocked in tests and replaced with a dynamic service
 *   discovery client (e.g., Consul, Kubernetes service DNS) in production.
 *
 * Routing rules (prefix-based):
 *   /api/v1/posts/*   → "PostService"
 *   /api/v1/follows/* → "FollowService"
 *   /api/v1/feed/*    → "FeedService"
 *   (anything else)   → null
 */
export interface IServiceRegistry {
  /**
   * Resolves the downstream service name for the given URL path.
   *
   * Uses prefix matching — the path `/api/v1/posts/create` matches the rule
   * `/api/v1/posts/*` and returns "PostService".
   *
   * @param path - The full URL path from the incoming request.
   * @returns The service name string, or `null` if no rule matches.
   *
   * @example
   * registry.resolve("/api/v1/feed/home")    // → "FeedService"
   * registry.resolve("/api/v1/unknown/route") // → null
   */
  resolve(path: string): string | null; // returns service name or null
}

/**
 * APIGateway — Validates JWT-style auth header, routes request to the
 * correct downstream service, and forwards injected `X-User-Id` header.
 *
 * RESPONSIBILITY:
 *   1. AUTH CHECK: If `authorization` header is missing → return 401 Unauthorized.
 *   2. TOKEN DECODE: Strip "Bearer " prefix, decode the base64 payload to
 *      extract the `sub` claim (userId). In production, also verify the
 *      JWT signature against a public key.
 *   3. ROUTING: Call `registry.resolve(req.path)` to find the target service.
 *      If null → return 404 Not Found.
 *   4. HEADER INJECTION: The userId becomes `X-User-Id` for downstream services.
 *   5. FORWARD: Return { status: 200, service, data: { forwardedUserId } }.
 *
 * ROUTING RULES (prefix-based):
 *   /api/v1/posts/*   → "PostService"
 *   /api/v1/follows/* → "FollowService"
 *   /api/v1/feed/*    → "FeedService"
 *
 * TDD Starter: method is intentionally not implemented — tests will fail (Red state).
 */
export class APIGateway {
  constructor(private registry: IServiceRegistry) {}

  /**
   * Handle an inbound HTTP-like request through the full gateway pipeline.
   *
   * FULL ALGORITHM (implement this step-by-step):
   *
   * ```
   * Step 1 — Authorization check:
   *   const authHeader = req.headers["authorization"]
   *   if (!authHeader || !authHeader.startsWith("Bearer ")):
   *     return { status: 401, service: "", error: "Unauthorized: missing or invalid Authorization header" }
   *
   * Step 2 — Token extraction & decoding:
   *   const token = authHeader.slice("Bearer ".length).trim()
   *   // Token format: "<base64payload>.<signature>"
   *   const [payloadB64] = token.split(".")
   *   const payloadJson = Buffer.from(payloadB64, "base64").toString("utf-8")
   *   const payload = JSON.parse(payloadJson)
   *   const userId = payload.sub   // "sub" is the standard JWT subject claim
   *   // If JSON.parse throws (malformed token), return 401
   *
   * Step 3 — Route resolution:
   *   const serviceName = this.registry.resolve(req.path)
   *   if (serviceName === null):
   *     return { status: 404, service: "", error: "Route not found: " + req.path }
   *
   * Step 4 — Inject X-User-Id and forward to downstream service:
   *   // In this simulation, we return a response indicating successful routing.
   *   // In production, this would make an HTTP call to the resolved service.
   *   return {
   *     status:  200,
   *     service: serviceName,
   *     data: {
   *       forwardedUserId: userId,
   *       forwardedPath:   req.path,
   *     },
   *   }
   * ```
   *
   * EDGE CASES TO HANDLE:
   *   - Header exists but is `"Bearer "` with no token → return 401.
   *   - Token has no "." separator (not a JWT format) → return 401.
   *   - Base64 payload decodes to invalid JSON → return 401.
   *   - `payload.sub` is missing or empty → return 401.
   *   - Path resolves to a valid service but body is null/undefined → allowed, pass through.
   *
   * @param req - The inbound GatewayRequest containing path, headers, and optional body.
   * @returns A GatewayResponse with status, service name, and optional error message.
   *
   * TDD Starter: method is intentionally not implemented — tests will fail (Red state).
   */
  async handleRequest(req: GatewayRequest): Promise<GatewayResponse> {
    const authHeader = req.headers["authorization"] || req.headers["Authorization"];
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      return {
        status: 401,
        service: "",
        error: "Unauthorized: missing or invalid Authorization header",
      };
    }

    const token = authHeader.slice("Bearer ".length).trim();
    if (!token) {
      return {
        status: 401,
        service: "",
        error: "Unauthorized: empty Bearer token",
      };
    }

    const parts = token.split(".");
    if (parts.length < 2) {
      return {
        status: 401,
        service: "",
        error: "Unauthorized: invalid JWT format",
      };
    }

    const payloadB64 = parts[0];
    let payload: any;
    try {
      const payloadJson = Buffer.from(payloadB64, "base64").toString("utf-8");
      payload = JSON.parse(payloadJson);
    } catch (e) {
      return {
        status: 401,
        service: "",
        error: "Unauthorized: invalid base64 or JSON payload",
      };
    }

    if (!payload || !payload.sub) {
      return {
        status: 401,
        service: "",
        error: "Unauthorized: missing subject claim",
      };
    }

    const userId = payload.sub;
    const serviceName = this.registry.resolve(req.path);
    if (serviceName === null) {
      return {
        status: 404,
        service: "",
        error: "Route not found: " + req.path,
      };
    }

    return {
      status: 200,
      service: serviceName,
      data: {
        forwardedUserId: userId,
        forwardedPath: req.path,
      },
    };
  }
}
