# TODO: Declare an encrypted Secret manifest
# apiVersion: v1
# kind: Secret
# metadata:
#   name: app-secrets
# type: Opaque
# data:
#   DB_USER: "cG9zdGdyZXM=" # base64 for postgres
#   DB_PASSWORD: "cG9zdGdyZXM=" # base64 for postgres
